name: 'Suggest a Feature'
description: 'Suggest a feature or enhancement for Torii'
type: 'Feature'
labels: [
  'enhancement'
]

body:
  - type: markdown
    attributes:
      value: '## Suggest A Feature Or Enhancement For Torii'
  - type: markdown
    attributes:
      value: >
        Thank you for wanting to help make Torii even better and feature packed for everyone!


        Before you continue, try to check if what you're suggesting has already been requested
        before, you can use the filter `is:issue label:enhancement type:Feature` in the Torii
        [issue tracker](https://github.com/shrine-maiden-heavy-industries/torii-hdl/issues)
        to search, or just [click here](https://github.com/shrine-maiden-heavy-industries/torii-hdl/issues?q=is%3Aissue%20label%3Aenhancement%20type%3AFeature)


        Also make sure to review the [Contribution Guidelines](https://github.com/shrine-maiden-heavy-industries/torii-hdl/blob/main/CONTRIBUTING.md#suggesting-features).

  - type: textarea
    id: feature-description
    attributes:
      label: 'Feature Description'
      description: >
        Please provide as detailed of a suggestion as possible, such as use cases and upsides, as well as
        any possible downsides or implementation issues can possibly foresee.


        For instance, if suggesting a new toolchain to support, please give us a rundown on things such as
        how easy it is to get a hold of, what platforms it supports, etc.


        For example, supporting the Synopsys Design Compiler would be lovely, but for the average maintainer
        and hobbyist, acquiring the tools to actually implement support for and test against is next to impossible.

    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 'Code of Conduct'
      description: >
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/shrine-maiden-heavy-industries/torii-hdl/blob/main/CODE_OF_CONDUCT.md)
        and [AI usage Policy](https://github.com/shrine-maiden-heavy-industries/torii-hdl/blob/main/CONTRIBUTING.md#ai-usage-policy).
      options:
        - label: 'I agree to follow the Torii Code of Conduct and AI Usage Policy'
          required: true
